rules:
  indent:
    - 2
    - 4
  quotes:
    - 2
    - double
  semi:
    - 2
    - always
  no-console:
    - 0
  no-var:
    - 2
  prefer-const:
    - 2
  prefer-template:
    - 2
  strict:
    - 2
    - global
env:
  es6: true
  node: true
extends: 'eslint:recommended'
